apiVersion: v1
kind: ConfigMap
metadata:
  name: ilmpolicy-config
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: filebeat
data:
  ilm-policy.json: |
    {
        "policy": {
            "phases": {
                "hot": {
                "actions": {}
                },
                "warm": {
                "min_age": "1d",
                "actions": {
                    "shrink": {
                    "number_of_shards": 1
                    },
                    "forcemerge": {
                    "max_num_segments": 1
                    }
                }
                },
                "delete": {
                "min_age": "30d",
                "actions":{
                    "delete": {}
                }
                }
            },
            "_meta": {
                "description": "Custom ILM policy using the hot and warm phases with a retention of 30 days",
                "managed": true
            }
        }
    }
