{{- if .Values.kibana.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eck-ingress
  namespace: {{ .Values.namespace }}
{{- if .Values.kibana.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.kibana.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
{{- if .Values.kibana.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.kibana.ingress.host }}
    secretName: kibana-eck-tls
{{- end }}
  rules:
  - host: {{ .Values.kibana.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: kibana-kb-http
            port:
              number: 5601
        pathType: ImplementationSpecific
{{- end }}
