{{- if .Values.filebeat.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.filebeat.modules.role_arn }}
{{- end }}
