rules:
  es_400: |-
    ---
    name: elast_alert_400
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 400"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_401: |-
    ---
    name: elast_alert_401
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 401"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_402: |-
    ---
    name: elast_alert_402
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 402"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_403: |-
    ---
    name: elast_alert_403
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 403"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_500: |-
    ---
    name: elast_alert_500
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 500"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_501: |-
    ---
    name: elast_alert_501
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 501"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_502: |-
    ---
    name: elast_alert_502
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 502"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

  es_503: |-
    ---
    name: elast_alert_503
    type: frequency
    index: filebeat-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "http.response.status_code : 503"
    alert:
    - "slack"
    slack:
    slack_webhook_url: ""

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "ECK-Services"
          operator: In
          values:
          - "true"
